### PR TITLE
[#57] Fix and deprecate PlainObjectCodec

### LINKED ISSUE #57: PlainObjectCodec rejects additional messages
PlainObjectCodec creates a json codec on demand, reads a stream and then returns a single object.
For this reason, I think, additional calls to `ReadObject`  may return empty results even though multiple objects
were sent.

```go
// WriteObject implements ObjectCodec.
func (PlainObjectCodec) WriteObject(stream io.Writer, v interface{}) error {
	return json.NewEncoder(stream).Encode(v)
}

// ReadObject implements ObjectCodec.
func (PlainObjectCodec) ReadObject(stream *bufio.Reader, v interface{}) error {
	return json.NewDecoder(stream).Decode(v)
}
```

To fix this, an object stream needs to store an encoder and a decoder:

```go
type PlainObjectStream struct {
	conn    net.Conn
	decoder *json.Decoder
	encoder *json.Encoder
	r       *bufio.Reader
	w       *bufio.Writer
	mu      sync.Mutex
}

func NewPlainObjectStream(conn net.Conn) ObjectStream {
	os := &PlainObjectStream{conn: conn, r: bufio.NewReader(conn), w: bufio.NewWriter(conn)}
	os.encoder = json.NewEncoder(os.w)
	os.decoder = json.NewDecoder(os.r)
	return os
}

func (os *PlainObjectStream) ReadObject(v interface{}) error {
	return os.decoder.Decode(v)
}

func (os *PlainObjectStream) WriteObject(v interface{}) error {
	os.mu.Lock()
	defer os.mu.Unlock()
	err := os.encoder.Encode(v)
	if err != nil {
		return err
	}
	os.w.Flush()
	return nil
}

func (os *PlainObjectStream) Close() error {
	return os.conn.Close()
}
```

In `jsonrpc2_test.go` the `TestClientServer` test doesn't pass with `PlainObjectCodec`, but passes with
this implementation of stream, `PlainObjectStream`.

The issue doesn't occur for other codes since, in my opinion, they are instantiated with a stream wrapped in `io.LimitReader` that protects the contents of the stream from being read by the decoder.

### PR DESCRIPTION
**Pull request by mnowotnik**
This change fixes a bug that causes PlainObjectCodec to
lose additional messages from stream. json.Decoder has
an internal buffer that reads more than one message, but
is discarded after every use. Now PlainObjectCodec reuses
encoder and decoder within a buffered stream, however
using it directly in your code retains the old, incorrect
behaviour.

A user should now use plainObjectStream if he needs
plain JSON-RPC 2.0 stream without headers.
`NewPlainObjectStream` method has been added for this reason.

fixes #57

### CODE REVIEW

File: stream.go [hunk 1]
```diff
@@ -163,15 +169,54 @@ func (VSCodeObjectCodec) ReadObject(stream *bufio.Reader, v interface{}) error {
 	return json.NewDecoder(io.LimitReader(stream, int64(contentLength))).Decode(v)
 }
 
+// DEPRECATED: use NewPlainObjectStream
 // PlainObjectCodec reads/writes plain JSON-RPC 2.0 objects without a header.
```
Comment (samherrmann) [inline stream.go:173]: I believe the deprecation notice should be formatted as follows:

```
// PlainObjectCodec reads/writes plain JSON-RPC 2.0 objects without a header.
//
// Deprecated: Use NewPlainObjectStream
```

* [Godoc: documenting Go code](https://go.dev/blog/godoc)
* [Example in Go's standard lib](https://github.com/golang/go/blob/master/src/bytes/bytes.go#L755-L759)

File: stream.go [hunk 2]
```diff
@@ -163,15 +169,54 @@ func (VSCodeObjectCodec) ReadObject(stream *bufio.Reader, v interface{}) error {
...
 }
+
+type plainObjectStream struct {
+	conn    io.Closer
+	decoder *json.Decoder
+	encoder *json.Encoder
+	mu      sync.Mutex
+}
+
+// plainObjectStream reads/writes plain JSON-RPC 2.0 objects without a header.
```
Comment (samherrmann) [inline stream.go:202]: This comment belongs on line 194, and comment here should be of the form `// NewPlainObjectStream ...`

File: stream.go (hunk 1 above)
Comment (mnowotnik) [reply stream.go:172]: Fixed

File: stream.go (hunk 2 above)
Comment (mnowotnik) [reply stream.go]: Fixed

File: stream.go [hunk 3]
```diff
@@ -164,14 +170,54 @@ func (VSCodeObjectCodec) ReadObject(stream *bufio.Reader, v interface{}) error {
...
+type plainObjectStream struct {
+	conn    io.Closer
+	decoder *json.Decoder
+	encoder *json.Encoder
+	mu      sync.Mutex
+}
+
+func NewPlainObjectStream(conn io.ReadWriteCloser) ObjectStream {
```
Comment (keegancsmith) [inline stream.go:204]: nit: doc string please

File: stream.go [hunk 4]
```diff
@@ -164,14 +170,54 @@ func (VSCodeObjectCodec) ReadObject(stream *bufio.Reader, v interface{}) error {
...
+	os := &plainObjectStream{conn: conn}
+	os.encoder = json.NewEncoder(conn)
+	os.decoder = json.NewDecoder(conn)
```
Comment (keegancsmith) [inline stream.go:207]: nit: just set all the fields when constructing the object

```suggestion
	os := &plainObjectStream{
		conn: conn,
		encoder: json.NewEncoder(conn),
		decoder: json.NewDecoder(conn),
	}
```

File: stream.go [hunk 5]
```diff
@@ -164,14 +170,54 @@ func (VSCodeObjectCodec) ReadObject(stream *bufio.Reader, v interface{}) error {
...
+	}
 	return json.NewDecoder(stream).Decode(v)
 }
+
+// plainObjectStream reads/writes plain JSON-RPC 2.0 objects without a header.
+type plainObjectStream struct {
+	conn    io.Closer
+	decoder *json.Decoder
+	encoder *json.Encoder
+	mu      sync.Mutex
```
Comment (keegancsmith) [inline stream.go:201]: I'm not sure you need the mutex. In every other example except buffered we don't use a mutex.

**Review by keegancsmith — APPROVED** [review]
LGTM. minor changes inline, will land once updated.

File: stream.go (hunk 5 above)
Comment (mnowotnik) [reply stream.go]: Added comment
